linters:

  HexLength:
    style: long

  ImportantRule:
    enabled: false

  NestingDepth:
    max_depth: 4

  PropertySortOrder:
    order:
      - align-content
      - align-items
      - align-self
      - animation
      - animation-delay
      - animation-direction
      - animation-duration
      - animation-fill-mode
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - appearance
      - backface-visibility
      - background
      - background-attachment
      - background-clip
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-size
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-collapse
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-spacing
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - box-shadow
      - box-sizing
      - caption-side
      - clear
      - clip
      - clip-path
      - color
      - columns
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-span
      - column-width
      - content
      - counter-increment
      - counter-reset
      - cursor
      - display
      - empty-cells
      - fill
      - filter
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - float
      - font
      - font-effect
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      - font-family
      - font-size
      - font-size-adjust
      - font-smoothing
      - font-stretch
      - font-style
      - font-variant
      - font-weight
      - height
      - hyphens
      - justify-content
      - letter-spacing
      - line-height
      - list-style
      - list-style-image
      - list-style-position
      - list-style-type
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - margin-collapse
      - margin-top-collapse
      - margin-right-collapse
      - margin-bottom-collapse
      - margin-left-collapse
      - mask
      - mask-image
      - max-height
      - max-width
      - min-height
      - min-width
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - opacity
      - order
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - overflow
      - overflow-x
      - overflow-y
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - page-break-inside
      - perspective
      - perspective-origin
      - pointer-events
      - position
      - top
      - right
      - bottom
      - left
      - quotes
      - resize
      - size
      - speak
      - src
      - stroke
      - stroke-dasharray
      - stroke-dashoffset
      - stroke-linecap
      - stroke-width
      - tab-size
      - table-layout
      - text-align
      - text-align-last
      - text-decoration
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-position
      - text-emphasis-style
      - text-indent
      - text-justify
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-rendering
      - text-outline
      - text-shadow
      - text-transform
      - text-wrap
      - touch-action
      - transform
      - transform-origin
      - transform-style
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - user-select
      - vertical-align
      - visibility
      - white-space
      - width
      - word-break
      - word-spacing
      - word-wrap
      - z-index
      - zoom

  SelectorDepth:
    max_depth: 4
